"""Add  issuance_manager, reception_manager

Revision ID: 17641677d90a
Revises: fb01db04f0a7
Create Date: 2023-12-06 20:18:08.052024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17641677d90a'
down_revision = 'fb01db04f0a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issuance_manager', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reception_manager', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('reception_manager')
        batch_op.drop_column('issuance_manager')

    # ### end Alembic commands ###
