"""is sold out

Revision ID: 755985b24796
Revises: d4b64c6ae9d2
Create Date: 2023-12-10 05:37:09.927362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755985b24796'
down_revision = 'd4b64c6ae9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sold_out', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_model', schema=None) as batch_op:
        batch_op.drop_column('is_sold_out')

    # ### end Alembic commands ###
