"""Update PrintWarehouse table

Revision ID: 839b7b366f6e
Revises: ab8a756531cf
Create Date: 2023-12-02 04:56:44.031596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839b7b366f6e'
down_revision = 'ab8a756531cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_warehouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.drop_column('model_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_warehouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
