"""Create working_hours and orders_completed

Revision ID: a7809a2464bc
Revises: 17641677d90a
Create Date: 2023-12-07 03:10:55.334602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7809a2464bc'
down_revision = '17641677d90a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orders_completed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('working_hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('working_hours')
        batch_op.drop_column('orders_completed')

    # ### end Alembic commands ###
