"""table Size

Revision ID: d4b64c6ae9d2
Revises: cff2dd31275f
Create Date: 2023-12-10 04:33:18.651759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4b64c6ae9d2'
down_revision = 'cff2dd31275f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_model_id', sa.Integer(), nullable=False),
    sa.Column('size_name', sa.String(length=50), nullable=True),
    sa.Column('remaining_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_model_id'], ['product_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_model', schema=None) as batch_op:
        batch_op.drop_column('remaining_quantity')
        batch_op.drop_column('available_sizes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_sizes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('remaining_quantity', sa.INTEGER(), autoincrement=False, nullable=True))

    op.drop_table('size')
    # ### end Alembic commands ###
