"""Add is_sold_out field to Products

Revision ID: fb01db04f0a7
Revises: 6d359c67971a
Create Date: 2023-12-03 13:50:39.766484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb01db04f0a7'
down_revision = '6d359c67971a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sold_out', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_sold_out')

    # ### end Alembic commands ###
